### PR TITLE
Update to Blender 2.80

### PR DESCRIPTION
**Pull request by RomanKornev**
Hey @troopy28!
I updated your code to support the new Blender 2.80.0 version.
It now works on both 2.79 and 2.80.
I also added installation instructions to Readme.

If you want to merge these changes, don't forget to update your `blender_optix_denoiser.py` in Google Drive link as well.

### CODE REVIEW

**Comment by troopy28** [comment]
Thanks a lot. I didn't have the time to work on this recently, really nice you could.

**Comment by RomanKornev** [comment]
Don't forget to update your `blender_optix_denoiser.py` in your Google Drive archive as well.
So that other people download the latest version.

**Comment by troopy28** [comment]
Yeah, that's done.

**Comment by RomanKornev** [comment]
Can you please double check?
When I download https://drive.google.com/drive/folders/10WNZuG4oaMIyLn0Klay7_DpZw5GzYHGF, it still uses the old version.

**Comment by troopy28** [comment]
Now it should be fine. I had not put it in the right place.

**Comment by RomanKornev** [comment]
Nice!

**Pull request merged**
